# In this notebook we are going to cover some of the most fundamental concepts of tensors using TensorFlow 

More specifically, we are going to cover: 
* Introduction to tensors 
* Getting information from tensors 
* Manipulating tensors 
* Tensors and Numpy 
* Using @tf.function (a way to speed up your regular python functions) 
* Using GPUs with TensorFlow(or TPUs) 
* Exercises to try for yourself

 # Introduction to Tensors

In [2]:
# import TensorFlow 
import tensorflow as tf 
print(tf.__version__)

2.9.2


In [3]:
# create tensors with tf.constant() 
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# number of dimensions 
scalar.ndim

0

In [5]:
# creata a vector 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# number of dimension 
vector.ndim

1

In [7]:
# create a matrix 
matrix = tf.constant([[2, 4,], 
                      [5, 6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [8]:
# number of dimensions 
matrix.ndim

2

In [9]:
# create another matrix 
a_matrix = tf.constant([[10., 7.], 
                        [3., 2.], 
                        [8., 9.]], dtype = tf.float16)
a_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# dimension
a_matrix.ndim

2

In [11]:
# create a tensor 
tensor = tf.constant([[[1., 2., 3.], 
                       [4., 5., 6.]], 
                      [[7., 8., 9.], 
                       [10., 11., 12.]], 
                      [[13., 14., 15.], 
                       [16., 17., 18.]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float32)>

In [12]:
tensor.ndim

3

### What we have created so far: 
* scalar: a single number 
* vector: a number with direction (e.g. wind speed and direction) 
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of number ( when n can be any number)

### Creating tensors with tf.variable()

In [13]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Let's try and change one of the elements in vhangeable tensor 
changeable_tensor[0] = 8

TypeError: ignored

In [16]:
# let's try .assign()
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [17]:
# Let's try and change one of the elements in unchangeable tensor
unchangeable_tensor[0] = 8

TypeError: ignored

In [ ]:
# let's try assign()
unchangeable_tensor[0].assign(8)

## creating random tensors 
tensors of random number with arbitrarily size

In [ ]:
# create 2 random(but the same) tensors
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42) 
random_2 = random_2.normal(shape=(3, 2))

# are they equal 
random_1, random_2, random_1 == random_2

### shuffle the order of elements in a tensor


In [18]:
# shuffle a tensor 
not_shuffled = tf.constant([[10., 7.], 
                        [3., 2.], 
                        [8., 9.]], dtype = tf.float16)
# shuffle our non_shuffled tensor 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 3.,  2.],
       [ 8.,  9.],
       [10.,  7.]], dtype=float16)>

In [19]:
# shuffle our non_shuffled tensor 
# global and operation level seed 
tf.random.set_seed(4) # global level seed
tf.random.shuffle(not_shuffled, seed = 42) # operation leevel seed

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  9.],
       [ 3.,  2.]], dtype=float16)>

## Other way to make tensors

In [20]:
# create a tensor of all ones 
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# create a tensor of all zeros 
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy arrays into tensors 
tensors can be run faster on GPU

In [22]:
import numpy as np
numpy_a = np.arange(1, 25, dtype = np.int32) 
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
tensor_a = tf.constant(numpy_a)
tensor_a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [24]:
# change the tensor shape 
tensor_b = tf.constant(numpy_a, shape = [2, 3, 4])
tensor_b

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensor

* Shape
* Rank 
* Dimension 
* Size

In [25]:
# dimension
tensor_a.ndim

1

In [26]:
# dimension 
tensor_b.ndim

3

In [27]:
# create a rank_4 tensor 
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [29]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.rank(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [30]:
# Get various attribute of our tensor 
print('Datatype', rank_4_tensor.dtype)
print('Number of dimensions', rank_4_tensor.ndim)
print('shape', rank_4_tensor.shape)
print('Elements along 0 axis', rank_4_tensor.shape[0])
print('Elements along 1 axis', rank_4_tensor.shape[-1])
print('Total number of elements', tf.size(rank_4_tensor))

Datatype <dtype: 'float32'>
Number of dimensions 4
shape (2, 3, 4, 5)
Elements along 0 axis 2
Elements along 1 axis 5
Total number of elements tf.Tensor(120, shape=(), dtype=int32)


### Indexing tensors

In [31]:
# get the first elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [33]:
# create a rank 2 tensor 
rank_2 = tf.constant([[11, 12], 
                      [13, 14]])
rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [34]:
rank_2.shape, rank_2.ndim

(TensorShape([2, 2]), 2)

In [35]:
# get the last item of each row 
rank_2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 14], dtype=int32)>

In [36]:
# add in extra dimension to our rank 2 tensor 
rank_3 = rank_2[..., tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[11],
        [12]],

       [[13],
        [14]]], dtype=int32)>

In [37]:
# alternative to tf.newaxis 
tf.expand_dims(rank_2, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[11, 12],
        [13, 14]]], dtype=int32)>

In [38]:

tf.expand_dims(rank_2, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[11, 12]],

       [[13, 14]]], dtype=int32)>

In [39]:

tf.expand_dims(rank_2, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[11],
        [12]],

       [[13],
        [14]]], dtype=int32)>

### Manipulating tensors 
**Basic Operations** 
'-', '+', '*', '/'

In [40]:
tensor = rank_2 
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [41]:
# addition
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [23, 24]], dtype=int32)>

In [42]:
# subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [43]:
# multiplication 
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [44]:
# division 
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.1, 1.2],
       [1.3, 1.4]])>

### Using TensorFlow built ins

In [45]:
# multiply 
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

### Matrix multiplication

In [46]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[277, 300],
       [325, 352]], dtype=int32)>

In [47]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[277, 300],
       [325, 352]], dtype=int32)>

In [48]:

# create a 3x2 matrix
X = tf.constant([[1, 2], [3, 4], [4, 5]])

# create a 3x2 matrix
y = tf.constant([[6, 7], [8, 9], [10, 11]])

In [49]:
tf.matmul(X, y)

InvalidArgumentError: ignored

In [50]:
X @ y

InvalidArgumentError: ignored

* it won't work because their shape violate the rules of matrix multiplication 

**Rule 1: Inner dimension must match** 

**Rule 2: The resulting matrix has the shape of the outer dimension**

In [55]:
# Let's change the shape of y 
y_reshape = tf.reshape(y, shape=(2, 3))

In [56]:
X @ y_reshape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[24, 27, 30],
       [54, 61, 68],
       [69, 78, 87]], dtype=int32)>

In [57]:
tf.matmul(X, y_reshape)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[24, 27, 30],
       [54, 61, 68],
       [69, 78, 87]], dtype=int32)>

In [58]:
# can do same with transpose 
y_transpose = tf.transpose(y)

In [59]:
y_reshape, y_transpose

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 6,  7,  8],
        [ 9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 6,  8, 10],
        [ 7,  9, 11]], dtype=int32)>)

- **reshape shuffle the elements** 
- **transpose flip the axis, change the rows to columns and vice versa**

In [60]:
# try matrix multiplication with transpose
X @ y_transpose

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 26, 32],
       [46, 60, 74],
       [59, 77, 95]], dtype=int32)>

In [61]:
X @ y_reshape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[24, 27, 30],
       [54, 61, 68],
       [69, 78, 87]], dtype=int32)>

- **the output are not the same**

**The dot Product** 

Matrix multiplication is also called the dot product 

- tf.matmul() 
- tf.tensordot()

In [62]:
X, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]], dtype=int32)>)

In [63]:
tf.tensordot(X, y_transpose, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 26, 32],
       [46, 60, 74],
       [59, 77, 95]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose(rather than reshape) one of the tensors to satisfy the matrix multiplication rules

### Changing the datatype of a tensor

In [64]:
# create a new tensor with the default datatype 
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [65]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [66]:
# change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [67]:
# change from int32 to float32 
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [68]:
E_16 = tf.cast(C, dtype = tf.float16)
E_16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

Aggregating tensors

In [70]:
# Get the absolute values 
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [71]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### The following form of Aggregation 
- **Minimum** 
- **Maximum** 
- **Mean** 
- **Sum**

In [77]:
# create a random tensor with alues between 0 and 100 
E = tf.constant(np.random.randint(20, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 38, 69, 21, 33, 45, 87, 78, 99, 70, 20, 67, 79, 61, 39, 64, 50,
       92, 50, 72, 54, 91, 21, 72, 77, 66, 86, 68, 92, 94, 82, 60, 57, 41,
       88, 69, 73, 86, 63, 83, 22, 26, 75, 51, 27, 58, 38, 31, 22, 34])>

In [78]:
E.shape, E.ndim, tf.size(E)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [79]:
# Minimum 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [80]:
# Maximum 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [81]:
# Mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=60>

In [82]:
# Sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3037>

In [86]:
# Variance 
tf.reduce_var(E) # won't work

AttributeError: ignored

In [87]:
# std 
tf.reduce_std(E) # won't work

AttributeError: ignored

In [88]:
# To find the variance, import tensorflow_probability 
import tensorflow_probability as tps 
tps.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=545>

In [91]:
# OR 
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=545.43243>

In [92]:
# the datatype must be float for std to work
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=23.354494>

### Positional Maximum and Minimum

In [94]:
# create a new tensor for positional max and min \
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
# postional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [96]:
# index on our largest value position 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [97]:
# max value of F 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [98]:
# check for equality 
assert F[tf.argmax(F)] == tf.reduce_max(F)

- **they are equal**

In [99]:
# postional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [100]:
# index on the value of the minimum 
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [101]:
# min value 
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [104]:
# create a new tensor for positional max and min \
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = [1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [105]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [108]:
G_sq = tf.squeeze(G) 
G_sq, G_sq.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One Hot Encoding

In [112]:
# create a list of indices 
some_list = [0, 1, 2, 3]

# one hot encode 
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [113]:
# specify on and off values for one hot encoding 
tf.one_hot(some_list, depth = 4, on_value = 'Yes', off_value = 'No')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

### Other mathematical functions

### **Squaring, log, square root**

In [117]:
# create a new tensor 
H = tf.range(1, 10, dtype = tf.float32) 
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [118]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

In [119]:
# square root 
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [120]:
# log 
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy

In [122]:
# create a tensor directly from numpy array 
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [123]:
# tensor back to numpy array 
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [124]:
# tensor to numpy array 
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [125]:
# The default types of each are slightly different 
numpy_J = tf.constant(np.array([3., 5., 7.])) 
tensor_J = tf.constant([3., 5., 7.])

# dtypes 
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)